### ISSUE TITLE
HOCR to PAGE converting howto?

### ISSUE THREAD

**Issue by jmokoistinen** [PRImA-Research-Lab/prima-page-converter#1]
Referencing to earlier problem at
[here](http://stackoverflow.com/questions/28591117/how-do-i-segment-a-document-using-tesseract-then-output-the-resulting-bounding-b)

> pctool="/Users/Me/Project/tools/JPageConverter 1.0"
> java -jar "$pctool/PageConverter.jar" -source-xml paper-3.xml -target-xml paper-3-hocrconvert.xml ->convert-to LATEST
> Unfortunately, I kept getting null pointers.
> 
> Could not convert to target XML schema format.
> ava.lang.NullPointerException
>    at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:126)
>   at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:65)
> ....

My run was resulting into exactly same error
sudo java -jar JPageConverter\ 1.0/PageConverter.jar -source-xml file.xml -target-xml result.xml -convert-to LATEST
Could not convert to target XML schema format.
java.lang.NullPointerException
    at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:126)
    at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:65)
Could not save target PAGE XML file: result.xml
java.lang.NullPointerException
    at org.primaresearch.dla.page.io.xml.XmlInputOutput.writePage(XmlInputOutput.java:144)
    at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:135)
    at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:65)

Maybe it is encoding problem? My documents are in UTF-8.
Any solutions?

**Comment by chris1010010** [comment]
Could you try the latest version, please? If that doesn't solve the problem, could you send me your xml files? Then I'd have a look.

**Comment by stweil** [comment]
@jmokoistinen, I think this issue can be closed.
