### ISSUE TITLE
negative input points

### ISSUE THREAD

**Issue by ghost** [PRImA-Research-Lab/prima-page-converter#10]
@chris1010010 
At times, the input Alto file might contain negative input points like this `="-90`
in that case, the converter fails.

Solution, add an option to deal with the negative points.

**Comment by chris1010010** [comment]
Hi, which option would be most useful in your case? Remove objects with negative coordinates? Try to cut off at 0?
PAGE forbids negative coordinates, so some form of correction is needed.

**Comment by deepseek** [comment]
hmmmm, perhaps the simplest is to remove the `-` negative sign

**Comment by ghost** [comment]
hmmmmm.... can you for now, 
- skip any region that contains a negative point 
While I speak with kermitt to fix the negative issue from pdfalto

**Comment by chris1010010** [comment]
Added -neg-coords command line option with two modes: removeObj (skip object with negative point(s)), toZero (change negative values to zero)

**Comment by ghost** [comment]
Thanks man
