### ISSUE TITLE
NullPointerException when trying to convert ALTO to PAGE

### ISSUE THREAD

**Issue by wrznr** [PRImA-Research-Lab/prima-page-converter#11]
I am trying to convert ALTO XML (2.0) to PAGE XML using version [1.5](https://www.primaresearch.org/tools/PAGEConverterValidator) as follows:
```shell
$ java -jar ~/Software/JPageConverter\ 1.5/PageConverter.jar -source-xml FULLTEXT/fileocr00013.xml -target-xml 0013.xml
Could not save target PAGE XML file: 0013.xml
java.lang.NullPointerException
	at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.writePage(PageXmlInputOutput.java:165)
	at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:188)
	at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:103)
```
ALTO file for testing [sample_alto.zip](https://github.com/PRImA-Research-Lab/prima-page-converter/files/3920628/sample_alto.zip).

Any hints would be highly appreciated!

**Comment by chris1010010** [comment]
Hi, the ALTO file is invalid. These are the error messages I get with XML Notepad:
![image](https://user-images.githubusercontent.com/7868102/70139402-52487680-168a-11ea-8dd2-5af65b0b4cd9.png)

**Comment by wrznr** [comment]
Good catch! Many thanks @chris1010010
