### ISSUE TITLE
No text lines in ALTO output

### ISSUE THREAD

**Issue by stweil** [PRImA-Research-Lab/prima-page-converter#13]
The conversion of an [example file](https://digi.bib.uni-mannheim.de/~stweil/FILE_0063_OCR-D-OCR-TESSEROCR.xml) from PAGE to ALTO creates an [ALTO file](https://digi.bib.uni-mannheim.de/~stweil/FILE_0063_OCR-D-OCR-TESSEROCR-ALTO.xml) without text lines:

    java -jar PATH/PageConverter.jar -source-xml FILE_0063_OCR-D-OCR-TESSEROCR.xml -target-xml FILE_0063_OCR-D-OCR-TESSEROCR-ALTO.xml -convert-to ALTO

Is ALTO support still incomplete?

**Comment by chris1010010** [comment]
Hi, what format is the input file and what does it contain?

**Comment by stweil** [comment]
The input is the PAGE XML file https://digi.bib.uni-mannheim.de/~stweil/FILE_0063_OCR-D-OCR-TESSEROCR.xml (link was also given above). It contains the layout information and OCR results for a single page from one of our books.

**Comment by chris1010010** [comment]
Okay, that explains it. Words (STRINGs) are mandatory in ALTO. So because there are no words in the PAGE XML, the ALTO exporter cannot add the text lines.

**Comment by stweil** [comment]
@kba, @bertsky, does that mean that we have to change ocrd-tesserocr-recognize to produce PAGE XML with words?

**Comment by stweil** [comment]
@chris1010010, thank you for your explanation.

**Comment by wrznr** [comment]
@stweil No. You can set `textequiv_level` to `word`.

**Comment by bertsky** [comment]
For anyone who traps into this fallacy from another angle (besides the special case ocrd-tesserocr-recognize): 
Consider using https://github.com/kba/page-to-alto, which can do much more conversions than the PRImA library, including dummy printspace, dummy lines and dummy regions, if needed.
