### ISSUE TITLE
Page Converter producing messy Unicode blocks

### ISSUE THREAD

**Issue by novacellus** [PRImA-Research-Lab/prima-page-converter#14]
When converting tesseract HOCR files, PageConverter sometimes produces some messy <Unicode> blocks. Instead of representing the entire TextRegion in separate XML element, the content of the region is inserted as a Unicode element in one of the <Word> elements with each word on a separate line and blank lines inserted randomly. I attach an hocr and  PAGE XML files for comparison: you can see the problem starting at par_7.

(tested with JPC 1.5 and 1.3)

[LiegnUB--142.hocr.txt](https://github.com/PRImA-Research-Lab/prima-page-converter/files/4649568/LiegnUB--142.hocr.txt)
[LiegnUB--142.xml.txt](https://github.com/PRImA-Research-Lab/prima-page-converter/files/4649569/LiegnUB--142.xml.txt)

**Comment by novacellus** [comment]
On closer analysis it seems that the issue occurs when JPageConverter stumbles upon `<span class='ocr_textfloat'>` instead of `<span class='ocr_line'>`.

**Comment by chris1010010** [comment]
Is that the correct nesting?
ocr_carea - ocr_par - ocr_textfloat - ocrx_word
Seems a bit odd.

**Comment by novacellus** [comment]
That's what the tesseract 4 produces, I'm afraid. Is there's something wrong with the ocr_textfloat being embedded in an ocr_par, at least standard-wise? In that case it would be the same problem as in https://github.com/tesseract-ocr/tesseract/issues/2596.

**Comment by chris1010010** [comment]
I'm not sure, the spec doc for hocr is not very clear. It's also strange that there's no text line in the float. Are they one line only? Have you tried Alto output?

**Comment by novacellus** [comment]
I ended up changing ocr_textfloat to ocr_line: ugly but worked for my purposes. In fact, ocr_textfloat may contain text words.

**Comment by chris1010010** [comment]
I do the same in the code now. As Tesseract outputs it, it virtually is a text line (even the ID says line). Will trickle through on next release

**Comment by novacellus** [comment]
Thanks. Just found another custom block that is processed incorrectly: ocr_header (seems to be perfectly compliant with the hOCR specification: http://kba.cloud/hocr-spec/1.2/).

**Comment by chris1010010** [comment]
The problem is I can't find in the specification what the allowed child elements are.
Does Tesseract output headers as text lines like the floats?

**Comment by novacellus** [comment]
It seems that there are four possibilities: ocr_header, ocr_textfloat, ocr_caption, ocr_line.
Cp. https://github.com/tesseract-ocr/tesseract/blob/master/src/api/hocrrenderer.cpp (211:225).
