### ISSUE TITLE
Error writing target ALTO XML file

### ISSUE THREAD

**Issue by kba** [PRImA-Research-Lab/prima-page-converter#16]
https://github.com/PRImA-Research-Lab/prima-page-converter/blob/56f960e77d1db84831e40f1d3ffa05a7c0b68898/src/org/primaresearch/dla/page/converter/PageConverter.java#L245

I'm running into this error and I'm stuck on what could be the problem - are there better diagnostics available if `writer.write` fails?

**Comment by kba** [comment]
[FILE_0001_OCR-D-OCR-CALAMARI.zip](https://github.com/PRImA-Research-Lab/prima-page-converter/files/5233675/FILE_0001_OCR-D-OCR-CALAMARI.zip)

Here's a failing PAGE-XML sample.

**Comment by chris1010010** [comment]
Thanks. Found and fixed the problem. Also the error output should be better now

**Comment by kba** [comment]
Many thanks for the quick and complete fix!

Can you make another release as well please, so we can update https://github.com/UB-Mannheim/ocr-fileformat and https://github.com/OCR-D/ocrd_fileformat ?

**Comment by chris1010010** [comment]
Just done the PageConverter release. Is that what you need?

 

C.

**Comment by kba** [comment]
It is indeed. Thank you very much!
