### ISSUE TITLE
error: package org.primaresearch.text.filter.TextFilter does not exist

### ISSUE THREAD

**Issue by mikegerber** [PRImA-Research-Lab/prima-page-converter#17]
I'm having trouble building prima-page-converter:

~~~
src/org/primaresearch/dla/page/converter/PageConverter.java:55: error: package org.primaresearch.text.filter does not exist
import org.primaresearch.text.filter.TextFilter;
                                    ^
src/org/primaresearch/dla/page/converter/PageConverter.java:56: error: package org.primaresearch.text.filter.TextFilter does not exist
import org.primaresearch.text.filter.TextFilter.TextObjectTypeFilterCallback;
                                               ^
~~~

Neither the [prima-core-libs](https://github.com/PRImA-Research-Lab/prima-core-libs) nor [prima-text](https://github.com/PRImA-Research-Lab/prima-text) contain these?

**Comment by mikegerber** [comment]
Judging from the release zip here, and the PrimaText.jar in there, it seems like https://github.com/PRImA-Research-Lab/prima-text is not complete (1 class in the source vs ~ 100 classes in the JAR)

**Comment by chris1010010** [comment]
That's correct, PrimaText is only partially open-source
