### ISSUE TITLE
"Error writing target PAGE XML file" on hOCR to PAGE conversion

### ISSUE THREAD

**Issue by novacellus** [PRImA-Research-Lab/prima-page-converter#2]
I keep getting "Error writing target PAGE XML file" error while trying to convert Tesseract hOCR files to PAGE XML.

`java -jar PageConverter.jar -source-xml input.hocr -target-xml output.xml  -convert-to LATEST`

In verbose mode it yields:
> [Loaded org.primaresearch.io.xml.IOError from file: mypath/JPageConverter_1.3/JPageConverter%201.3/lib/PrimaIo.jar]
[Loaded org.primaresearch.io.xml.XmlValidationError from file:mypath/JPageConverter_1.3/JPageConverter%201.3/lib/PrimaIo.jar]
Error writing target PAGE XML file

The same bug occurs whether I'm using the precompiled or source version of the JPageConverter. Changing .hocr extension to .xml doesn't help.

I've changed input.hocr extension to input.txt since GitHub seems not to accept .xml uploads: [input.txt](https://github.com/PRImA-Research-Lab/prima-page-converter/files/2038918/input.txt)

**Comment by chris1010010** [comment]
I have tracked this down to a problem in the HOCR reader. I cannot cope with the extended information in:
>> title="bbox 259 269 2539 332; baseline -0 -17; x_size 62; x_descenders 17; x_ascenders 16" <<
Will be fixed in next release

**Comment by chris1010010** [comment]
Now fixed in core libs code (but not in binaries/jars)

**Comment by novacellus** [comment]
Great! Thank you! One small thing then: where should I look for the PrimaText library referenced in the .classpath: `<classpathentry combineaccessrules="false" kind="src" path="/PrimaText"/>` ? Of course, it works just fine if PrimaText.jar is referred in the .classpath and the above line just commented out.

**Comment by chris1010010** [comment]
In the PageConverter release or here http://www.primaresearch.org/tools/PerformanceEvaluation
