### ISSUE TITLE
"Could not save target PAGE XML file:"

### ISSUE THREAD

**Issue by vndee** [PRImA-Research-Lab/prima-page-converter#3]
I have used JPageConverter 1.4 to convert older PAGE XML file to the LATEST PAGE XML format. But I've got an error:
> java -jar PageConverter.jar -source-xml 00000663.xml -target-xml out.xml -convert-to LATEST

> Could not convert to target XML schema format.
java.lang.NullPointerException
        at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:165)
	at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:94)
Could not save target PAGE XML file: out.xml
java.lang.NullPointerException
	at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.writePage(PageXmlInputOutput.java:162)
	at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:174)
	at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:94)

My PAGE XML file 00000663.xml from PRImA Document Layout Analysis corpus.
Please help me. Thanks!

**Comment by chris1010010** [comment]
Hi,
These are very old PAGE files with a 2009 schema. Reading those is currently not supported. But you can open the files with prefix pc-... (they are 2010 PAGE XML version).
I'll make a note, thanks.

**Comment by chris1010010** [comment]
I had a closer look. I actually found a bug (new release soon) and the 2009 PAGE XML format is supported after all. But the 00000663.xml is not in that format, even though the namespace at the top of the file suggests so. I assume something has gone wrong back then when they converted to PAGE 2009.

**Comment by chris1010010** [comment]
Closing this, see comment above

**Comment by chris1010010** [comment]
> I have used JPageConverter 1.4 to convert older PAGE XML file to the LATEST PAGE XML format. But I've got an error:
> 
> > java -jar PageConverter.jar -source-xml 00000663.xml -target-xml out.xml -convert-to LATEST
> 
> > Could not convert to target XML schema format.
> > java.lang.NullPointerException
> > at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:165)
> > at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:94)
> > Could not save target PAGE XML file: out.xml
> > java.lang.NullPointerException
> > at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.writePage(PageXmlInputOutput.java:162)
> > at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:174)
> > at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:94)
> 
> My PAGE XML file 00000663.xml from PRImA Document Layout Analysis corpus.
> Please help me. Thanks!

@vndee,
I think I fixed those files, including 00000663.xml. You can re-download the set. Hope it works now
