### ISSUE TITLE
PDF to Page-xml

### ISSUE THREAD

**Issue by mrocr** [PRImA-Research-Lab/prima-page-converter#5]
Will you consider the ability to convert a PDF file to a Page-xml file..

**Comment by chris1010010** [comment]
A conversion would not be easy. At the moment we don't have the resources for this. The only possible way is to convert to an image and run TesseractToPage (on our website) to OCR

**Comment by mrocr** [comment]
Thanks for your consideration

**Comment by kba** [comment]
https://github.com/PRImA-Research-Lab/prima-page-to-pdf ?

**Comment by chris1010010** [comment]
That's the opposite ;-)

**Comment by kba** [comment]
> That's the opposite ;-)

True, but wouldn't it a possible workflow:

```
pdftoimages
[preprocessing]
ocrd-tesserocr-recognize
prima-page-to-pdf to sandwich text and results?
```

Really curious, haven't had the time yet to deal with this, but it's certainly a desired feature for many users. Many libraries also offer a bulk PDF download which is easier to scrape than the mets.xml (if users even know about that option).

**Comment by chris1010010** [comment]
Yes, that's possible of course (see my entry from May). But you throw away a lot of information (the text) and the results will only be as good as Tesseract

**Comment by BobLd** [comment]
Maybe have a look at the `PageXmlTextExporter` class in [PdfPig](https://github.com/UglyToad/PdfPig) (in C#). See the [wiki](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#export) for more info. It's still an early version but might help...
