### ISSUE TITLE
Error writing target PAGE XML file

### ISSUE THREAD

**Issue by ghost** [PRImA-Research-Lab/prima-page-converter#9]
@chris1010010 
When trying to convert an alto xml file to page-xml, I am getting an error of:
```
Error writing target PAGE XML file
```
I have validated my alto xml files, and it successfully did using:
```
wget https://raw.githubusercontent.com/kermitt2/pdfalto/master/schema/alto.xsd
xmllint --noout --schema alto.xsd output.xml
output.xml validates
```
My files attached 
[test.zip](https://github.com/mauvilsa/nw-page-editor/files/3612767/test.zip)

Waiting for your reply

**Comment by chris1010010** [comment]
Hi, the problem is that there are some negative coordinates, which is not allowed in PAGE XML. Admittedly, the converter should change or remove those

**Comment by ghost** [comment]
@chris1010010 Thanks for the hint, I was able to solve it.
But I am hoping that you integrate the negative coordinates removal option in the converter.
Keep up the good work.
